name: Spec tests

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:

  spec:
    name: Spec test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Update gems
        run: bundle update
      - name: Run tests
        run: bundle exec rspec
